### ISSUE TITLE
Working?

### ISSUE THREAD

**Issue by tristen** [osmlab/osm-stream#5]
When I run a server and hit index.html everything is peachy and [data.length](https://github.com/osmlab/osm-stream/blob/gh-pages/site.js#L7) is [inserted here](https://github.com/osmlab/osm-stream/blob/gh-pages/index.html#L9)

However, after re-installing + re-bundling the script no longer returns data. Also, it looks like all three demo sites no longer work: https://github.com/osmlab/osm-stream#as-seen

**Comment by tmcw** [comment]
[Please improve this bug report](http://www.macwright.org/report-a-bug/)
- include javascript backtraces
- link to actual pages
- be extremely specific about the issue

**Comment by tristen** [comment]
lol

**Comment by iandees** [comment]
There was an unannounced API change in the Overpass server a few months ago that might have affected this. I patched show-me-the-way's copy of osm-stream here: https://github.com/osmlab/show-me-the-way/commit/8c1b0c6d3e1cfdf156a356a98ca50acbeff131f7

**Comment by iandees** [comment]
Also they were fiddling with CORS support back then. I'm pretty sure I got them to fix it, but maybe they broke it again.

show-me-the-way works if you give it enough time, though.
