### ISSUE TITLE
The license data of this repository is inconsistant

### ISSUE THREAD

**Issue by emacsen** [osmlab/osm-stream#8]
The LICENCE file says that the software is public domain while the package.json file says it's BSD.

**Comment by emacsen** [comment]
Oops, my comment should be here, not the patch.

Other authors would need to sign off on any change.

**Comment by tmcw** [comment]
Reopened. Please adopt this project if you want it to change.

**Comment by emacsen** [comment]
I'll see if I can get the change I need easily (which is to separate this out from the browser dependency so it can run on node).

**Comment by jfirebaugh** [comment]
As one of the four contributors: I don't care what the license is. Public domain is fine.

**Comment by emacsen** [comment]
Just realize that PD also means someone can wipe your credit from the work, in addition to re-licensing.

**Comment by tmcw** [comment]
We understand how licenses work.

**Comment by emacsen** [comment]
@tmcw can you try not to be rude?

**Comment by tmcw** [comment]
Licensing is up to the people who have contributed to the repo; all we're trying to do is +1 a pretty straightforward change. We've been around the block before, understand licenses, and don't need unsolicited input about how liberal licenses are liberal.

**Comment by iandees** [comment]
:+1: to public domain.

**Comment by tristen** [comment]
Closing, `public domain` it is!
